FROM ubuntu:20.04


RUN apt update && apt install python3-pip iputils-ping telnet python-is-python3 -y && \
    apt-get clean autoclean && \ 
    apt-get autoremove --yes && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/

RUN useradd -ms /bin/bash appuser &&  mkdir /app && chown -R appuser:appuser /app

USER appuser

WORKDIR /app

COPY --chown=appuser:appuser  docker_homework/lib_catalog/. .

RUN pip3 install -r ./requirements.txt

RUN echo "#!/bin/bash -ex\npython manage.py migrate\npython manage.py runserver 0.0.0.0:8000" > run.sh && chmod +x run.sh

EXPOSE 8000

CMD ["./run.sh"]
