FROM ubuntu:latest

RUN apt update && apt install python3-pip iputils-ping telnet python-is-python3 -y
WORKDIR /app
COPY docker_homework/lib_catalog/. .

RUN python3 --version && pip3 --version
RUN pip3 install -r ./requirements.txt

RUN echo "#!/bin/bash -ex\npython manage.py migrate\npython manage.py runserver 0.0.0.0:8000" > run.sh && chmod +x run.sh

EXPOSE 8000

CMD ["./run.sh"]
